### ISSUE TITLE
Set up GA tracking for all academic school sites and SITS admissions

### ISSUE THREAD

**Issue by lrhm-unikent** [unikent/of-course#443]
Angela wants to track users from academic schools, through to completing their application forms. To do this we need to identify:

 - [x] schools that have separate domains/sub-domains to kent.ac.uk 
 - [ ] add the 'central' GA tracking code to these sites
 - [ ] set up the appropriate goals/funnels to track conversions

@mb324-unikent @Angelamariewatson Just wanted to record this somewhere so it doesn't get forgotten

**Comment by eg270-unikent** [comment]
@aw285-unikent as this is one for SITS, can we close it on GitHub and move to FootPrints? (as SITS don't have access to this repo)?

**Comment by aw285-unikent** [comment]
hi @eg270-unikent keeping @STC21-UniKent in the loop on this one as he has been following it up since I posted this. Sam - is this already a footprints issue?

**Comment by aw285-unikent** [comment]
@eg270-unikent , @STC21-UniKent is working on this with the SITS team so I will close this. We'll raise a seperate ticket if we need web dev's assistance in the future on this one.
