### ISSUE TITLE
Rollout (Fees)

### ISSUE THREAD

**Issue by ghost** [unikent/of-course#495]
- [x] #441 Prep for launch
- [x] #494 Check caveat text & disclaimer are correct on live. Ensure international/year abroad text is updated
- [x] Ensure upto data FEE csv file is ready on live
- [x] Deploy latest OC & PP
- [x] #440 Make 2015 default UG year
- [x] #452 Flush front end caches
- [x] #439 Remove 2015 .htaccess
- [x] #456 Update pantheon config to say 2015 UG
- [x] #486 Move old index page to 2014 folder, put index-new in place
- [x] Check CRONS
- [x] #438 - Update collections
