### ISSUE TITLE
Checklist for a new prospectus launch

### ISSUE THREAD

**Issue by eg270-unikent** [unikent/of-course#746]
I'm just creating this ticket as a reminder for when we do a prospectus rollover (UG - February, PG - August/September).

- [ ] run rollover script on www-test
- [ ] roll over overridable fields (if using capistrano task this should be done for you)
- [ ] Once above is QA'd, run rollover script on www-live
- [ ] update CRON to pull in SITS deliveries for new rollover year (i.e. UG 2017 etc)
- [ ] day after rollover on live, check CRON ran and deliveries came over from SITS ok
- [ ] On launch date, shouldn't be anything for Webdev to do, EMS will need to update PP years to rollover prospectus
  - This will also update the snippet where people are using 'current' as the year
  - Links to old prospectus may need updated:
    - UG prospectus - 2 years run in parallel until mid-September
    - PG prospectus - only 1 prospectus advertised at once *but* old webpages still active but should not be linked to. We don't take these pages down from the web server.

**Comment by eg270-unikent** [comment]
Closing this as we should be able to search for this ticket when we need to :+1:

**Comment by aw285-unikent** [comment]
@eg270-unikent Would it be possible to add a task to this please:

to un-check any programmes that have had the 'new programme' check-box checked on the new prospectus year (eg when doing the clone). I forgot to request this for PG so will do it manually but it would be good if this could be done programatically as part of the rollover if possible. Thanks, Angela

**Comment by eg270-unikent** [comment]
@aw285-unikent I've added that to the checklist above.
